firecrawl/firecrawl

apps/api/src/index.ts

[Bugfix] added normalized apikey to craw/status route

---

CONTRIBUTING.md

I changed the readme so that it does not link to nonexistent contributors.me

Caleb: fixing some documentation and rebuilding the server

---

apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/tsconfig.json
apps/js-sdk/firecrawl/types/index.d.ts

also updated the JS-SDK version to 0.0.11

[Feat] Added type declarations

---

apps/api/src/controllers/search.ts
apps/api/src/lib/entities.ts
apps/api/src/search/googlesearch.ts
apps/api/src/search/index.ts
apps/api/src/search/serper.ts

Serper params

---

apps/api/src/controllers/search.ts
apps/api/src/lib/entities.ts
apps/api/src/search/googlesearch.ts
apps/api/src/search/index.ts
apps/api/src/search/serper.ts

```
{
query: "what is a coconut?",
searchOptions:{
limit: 10,
tbs: "qdr:y",
filter: 1,
lang: "en",
country: "us",
location: "Hawaii, United States"
}
}
```

Support for tbs, filter, lang, country and location with Serper search.

---

apps/api/src/scraper/WebScraper/utils/blocklist.ts

FireCrawl should be able to scrape LinkedIn Articles (/pulse/*)

[Feat] Added allowed urls

---

apps/js-sdk/firecrawl/build/index.js
apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/index.ts
apps/js-sdk/firecrawl/types/index.d.ts
apps/js-sdk/package-lock.json
apps/js-sdk/package.json

/search support in node sdk

---

apps/api/src/scraper/WebScraper/single_url.ts
apps/api/src/scraper/WebScraper/utils/custom/website_params.ts

Websites with more strick rules requires custom params to work.
Todo:

Specific website params support

---

apps/api/src/scraper/WebScraper/single_url.ts
apps/api/src/scraper/WebScraper/utils/custom/website_params.ts

https://github.com/mendableai/firecrawl/discussions/51#discussioncomment-9217619
merge #83 first
ccing @igalmarino

Greenpay fixes

---

apps/python-sdk/firecrawl/firecrawl.py

[Feat] Implemented retry attempts to handle 502 errors

---

.github/workflows/ci.yml
.github/workflows/fly.yml
CONTRIBUTING.md
apps/api/.env.example
apps/api/package.json
apps/api/pnpm-lock.yaml
apps/api/src/__tests__/e2e_noAuth/index.test.ts
apps/api/src/services/logging/log_job.ts
apps/api/src/services/posthog.ts

Adding Posthog logging to log_job

Add Posthog Logging

---

apps/api/src/__tests__/e2e_withAuth/index.test.ts
apps/api/src/controllers/crawl.ts
apps/api/src/controllers/crawlPreview.ts
apps/api/src/controllers/scrape.ts
apps/api/src/controllers/search.ts
apps/api/src/lib/entities.ts
apps/api/src/main/runWebScraper.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/single_url.ts
apps/api/src/types.ts

[Feat] Added includeHTML option

---

apps/api/src/__tests__/e2e_withAuth/index.test.ts
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/index.ts

[Feat] Added max depth option

---

LICENSE

Hey everyone!
We've got some critical updates and need your help. As Firecrawl grows (we've crossed 2.6k stars!), we're thinking about sustainability and how to protect our project. We started with the Apache license because it's open and flexible. But, to ensure we can sustainably maintain this repository, we're switching to AGPL.
We're moving to the GNU Affero General Public License (AGPL). It's still **open-source** and ensures that anyone who uses our software, even as a service over a network, shares their improvements. This helps everyone benefit and keeps the ecosystem fair. If we didn't use this license, companies could swoop in and sell their own versions of firecrawl without even contributing to the repository or attributing our collective work! 
If you've contributed to …

Switching to AGPL - We Need Your Consent!

---

apps/api/openapi.json

Closes #107 and https://github.com/hellofirecrawl/docs/issues/1

[Doc] Added default value for crawlOptions.limit

---

apps/api/src/__tests__/e2e_withAuth/index.test.ts
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/single_url.ts
apps/api/src/services/queue-worker.ts

Known bug: there seems to be a duplication of urls when crawling, working on fixing it.

feat: 4x-5x faster crawler (fast mode)

---

apps/api/package.json
apps/api/pnpm-lock.yaml
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/utils/__tests__/docxProcessor.test.ts
apps/api/src/scraper/WebScraper/utils/docxProcessor.ts

closes #157
Returns content not markdown, but it is still very clean and well-formatted just like the pdf.

feat: Docx Support

---

README.md

Update README.md: Typo fix

---

apps/api/src/scraper/WebScraper/crawler.ts

Add additional file extensions.

Add additional file extensions to crawler.ts

---

apps/api/src/scraper/WebScraper/utils/blocklist.ts

helps solve #161 for now...
Not a great way of doing it, but we can revise it later. For now it should suffice.

feat: Allow privacy/legal/ other pages in social media websites 

---

apps/python-sdk/firecrawl/firecrawl.py

[Bug] Added data check for python SDK

---

apps/api/src/controllers/auth.ts

- Fix #81 
- Added better error code for when rate limit exceeded including consumed/remaining points, reset date and retry-after seconds

Feat: Provide more details for 429 error msg

---

apps/api/src/controllers/search.ts

It solves #73 by searching 1.5 * num_results and then returning num_results

Limit on /search is not deterministic

---

apps/api/src/scraper/WebScraper/single_url.ts

[Feat] Added custom scraping conditions for readme docs

---

apps/js-sdk/firecrawl/src/index.ts

[Fix] Changed timeout parameter name on js sdk

---

apps/api/src/scraper/WebScraper/single_url.ts

[Feat] Added custom scraping for google-drive pdf usecase

---

apps/api/src/scraper/WebScraper/custom/handleCustomScraping.ts
apps/api/src/scraper/WebScraper/single_url.ts

[Feat] Added scroll xpaths on fire-engine for handling readme docs

---

apps/api/src/__tests__/e2e_withAuth/index.test.ts
apps/api/src/scraper/WebScraper/custom/handleCustomScraping.ts
apps/api/src/scraper/WebScraper/single_url.ts

able to get more content than before #235

[Feat] Improved the scrape for gdrive pdfs

---

apps/api/src/lib/entities.ts
apps/api/src/main/runWebScraper.ts
apps/api/src/scraper/WebScraper/index.ts

Partial Data Sliding window of 50

---

apps/api/.env.example
apps/api/package.json
apps/api/pnpm-lock.yaml
apps/api/src/controllers/auth.ts
apps/api/src/services/billing/credit_billing.ts
apps/api/src/services/notification/email_notification.ts
apps/api/src/types.ts

feat: Transactional emails for rate limits and credit limits

---

apps/python-sdk/firecrawl/firecrawl.py

Just a minor patch to align param name between the two sdk.

Fix 208 py sdk interval poll name

---

apps/api/openapi.json
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/utils/__tests__/replacePaths.test.ts
apps/api/src/scraper/WebScraper/utils/replacePaths.ts

Fixed bugs associated with absolute path replacements

---

apps/api/src/services/webhook.ts

Only fetch webhook from db if self host webhook not set and using db auth

---

.github/workflows/clean-before-24h-complete-jobs.yml
apps/api/src/index.ts

[Feat] Added route to clean completed jobs and a github action cron that triggers every 24h

---

apps/api/src/services/queue-worker.ts
apps/api/src/services/webhook.ts

[Feat] Added jobId to webhook data

---

apps/api/fly.toml
apps/api/src/__tests__/e2e_noAuth/index.test.ts
apps/api/src/__tests__/e2e_withAuth/index.test.ts
apps/api/src/index.ts
apps/api/src/services/redis.ts

Currently our node app instance is only taking advantage of 1 core of our machines, leading to various inefficiencies. This approach allows us to run # of worker processes in parallel (multiple instances of our server in a single machine) which helps boost efficiency and performance.

Clusters support to scale our API to # of CPUs running

---

apps/api/openapi.json
apps/api/src/__tests__/e2e_withAuth/index.test.ts
apps/api/src/controllers/crawl.ts
apps/api/src/controllers/crawlPreview.ts
apps/api/src/controllers/search.ts
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/single_url.ts

Added pageOptions.removeTags

---

apps/js-sdk/firecrawl/README.md
apps/js-sdk/firecrawl/build/index.js
apps/js-sdk/firecrawl/package-lock.json
apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/index.ts
apps/js-sdk/firecrawl/types/index.d.ts
apps/js-sdk/package-lock.json

This pull request adds a feature to the Node.JS SDK so that it now supports local instances of Firecrawl, rather than hardcoding a single api url.

Added local host support for the javascript SDK

---

apps/api/src/scraper/WebScraper/custom/handleCustomScraping.ts

[Bug] Fixed the regex test for google drive pdf files

---

apps/api/src/controllers/crawl.ts
apps/api/src/controllers/scrape.ts
apps/api/src/lib/default-values.ts

[Bug] Added default values and fixed pdf bug

---

apps/api/src/__tests__/e2e_full_withAuth/index.test.ts
apps/api/src/__tests__/e2e_withAuth/index.test.ts

[Test] Added E2E tests for checking metadata values

---

apps/api/openapi.json
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/utils/__tests__/removeUnwantedElements.test.ts
apps/api/src/scraper/WebScraper/utils/removeUnwantedElements.ts

pageOptions.onlyIncludeTags param

---

apps/api/src/__tests__/e2e_full_withAuth/index.test.ts
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/index.ts

[Proposal] new feature allowExternalContentLinks

---

.github/dependabot.yml

In other to be up to date regarding dependencies across apps.

[PROPOSAL] (deps): making sure all deps are always up to date

---

docker-compose.yaml

a small proposal to have a more sync docker-compose for envs vars between the api and the service

[PROPOSAL] (docker-compose) regroup envs vars between services 

---

.gitignore
apps/playwright-service-ts/README.md
apps/playwright-service-ts/api.ts
apps/playwright-service-ts/helpers/get_error.ts
apps/playwright-service-ts/package.json
apps/playwright-service-ts/tsconfig.json

Hi guys!
this is one of the side projects that I made to scrape
feel free to merge it at Firecrawl repo
I also adapted to run as a firecrawl service by `PLAYWRIGHT_MICROSERVICE_URL=http://localhost:3000/scrape`
working great for me

new playwright service

---

apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/global.ts
apps/api/src/scraper/WebScraper/scrapers/fetch.ts
apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
apps/api/src/scraper/WebScraper/scrapers/playwright.ts
apps/api/src/scraper/WebScraper/scrapers/scrapingBee.ts
apps/api/src/scraper/WebScraper/single_url.ts
apps/api/src/services/logging/scrape_log.ts
apps/api/src/types.ts

Logging for all scraper methods

---

apps/api/src/scraper/WebScraper/utils/custom/website_params.ts

@tomkosm improvements already makes this work without the capcha stuff
Closes #342

[Feat] Added veeva to special case params

---

apps/api/src/controllers/crawl-cancel.ts

Should fix https://github.com/mendableai/firecrawl/issues/372 :)

Only check Supabase if configured to when cancelling job

---

apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/sitemap.ts

[Feat] Added fire-engine fallback for getting sitemaps

---

apps/api/src/services/logging/crawl_log.ts
docker-compose.yaml

[BUG] Fixed docker self hosting issue

---

apps/api/src/index.ts
apps/api/src/main/runWebScraper.ts
apps/api/src/services/alerts/index.ts
apps/api/src/services/alerts/slack.ts

Slack Alerts for when queue is over capacity

---

apps/api/src/scraper/WebScraper/utils/custom/website_params.ts

Notion Website Fixes

---

apps/api/src/controllers/admin/queue.ts
apps/api/src/controllers/admin/redis-health.ts
apps/api/src/index.ts
apps/api/src/routes/admin.ts

Admin router + Improve redis notifications

---

SELF_HOST.md

related to https://github.com/hellofirecrawl/docs/pull/11
closes #476

[Feat] Better self hosting guide

---

apps/api/src/scraper/WebScraper/crawler.ts

[Bug] Issue with crawl going beyond Limit

---

apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/utils/docxProcessor.ts
apps/api/src/scraper/WebScraper/utils/pdfProcessor.ts

Added try catches for pdfs and docx and fixed log events.
Closes #466

[Bug] pdfs and logging pdf events, also added trycatchs for docx

---

apps/api/src/services/supabase.ts
docker-compose.yaml

Set LOGGING_LEVEL to environment, and suppressed repetitive logs in supabase

Improve logs

---

SELF_HOST.md
apps/api/.env.example

Update redis urls in example .env

---

apps/api/src/__tests__/e2e_withAuth/index.test.ts

now passing
- added 1s await
- check for empty array or null for cancel test
- removed fast mode test

Fixed e2e tests

---

docker-compose.yaml

see
https://forums.docker.com/t/docker-compose-yml-version-is-obsolete/141313

Removed obsoleted declaration

---

apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
apps/api/src/scraper/WebScraper/single_url.ts

sending params to fireengine for beta customers

added variables to beta customers

---

apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts

[Feat] Added check job and cancel to fire-engine requests

---

apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts

@calebpeffer this solves the bug you said earlier today
the response looks like this:
```json
{
"success": true,
"data": {
"content": "",
"markdown": "",
"html": "",
"linksOnPage": [],
"metadata": {
"sourceURL": "https://ajskhdioauhsdoas.com/",
"pageStatusCode": 404,
"pageError": "Dns resolution error for hostname: ajskhdioauhsdoas.com"
}
},
"returnCode": 200
}
```

[Bug] Added a way for dealing with DNS without IP resolution

---

apps/js-sdk/firecrawl/package-lock.json
apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/__tests__/v1/e2e_withAuth/index.test.ts
apps/js-sdk/firecrawl/src/index.ts

[Bug] Fixed screenshot typo and added test for fullpage screenshot

---

.vscode/settings.json
apps/rust-sdk/Cargo.lock
apps/rust-sdk/Cargo.toml
apps/rust-sdk/README.md
apps/rust-sdk/examples/example.rs
apps/rust-sdk/src/crawl.rs
apps/rust-sdk/src/document.rs
apps/rust-sdk/src/error.rs
apps/rust-sdk/src/lib.rs
apps/rust-sdk/src/map.rs
apps/rust-sdk/src/scrape.rs
apps/rust-sdk/tests/e2e_with_auth.rs

Rust SDK 1.0.0

---

apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/index.ts

Improves error handler in Node SDK to return the status code

---

apps/api/Dockerfile

Make sure the entrypoint script has the correct line endings

---

apps/api/src/scraper/WebScraper/scrapers/playwright.ts

Fixed Issue #734 : timeout parameter not passed to playwright service

Fixed Issue #734

---

apps/api/src/controllers/v1/crawl.ts

bugfix: self-host crawling doesnt respect limit

---

apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/index.ts
apps/python-sdk/firecrawl/__init__.py
apps/python-sdk/firecrawl/firecrawl.py

closes #708
related to https://github.com/hellofirecrawl/docs/pull/25

[SKD] Cancel Crawl

---

README.md

This pull request addresses spelling errors in the README file of our R project.
- Corrected misspelling of extremly to extremely
- Corrected misspelling of capabilites to capabilities
- Corrected misspelling of Intracting to Interacting
This fix is not related to any existing issue. It's a minor typo that I noticed while reviewing the README.
Thank you for considering this contribution.

Spelling Corrections in README

---

apps/api/v1-openapi.json

related to https://github.com/hellofirecrawl/docs/pull/26
closes #764

[Doc] Better explained how includePaths and excludePaths work

---

README.md

Added the contributors section in the readme. Also added a back to top button to help in going to the start of the readme.

ADDED : Contributors and Back to top 

---

apps/api/src/controllers/v1/crawl-status-ws.ts
apps/api/src/controllers/v1/crawl-status.ts

for a 153795 docs crawl, went from ~131000ms to 38ms

[Feat] Performance improvements crawl status filters

---

apps/api/src/__tests__/e2e_v1_withAuth/index.test.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/scraper/WebScraper/utils/metadata.ts

Make sure all tags are included - even if not present in our types.

Return all the website metadata

---

apps/api/src/lib/LLM-extraction/helpers.ts

[Bug] encoding error for special token

---

apps/python-sdk/firecrawl/firecrawl.py

[BUG-SDK] missing error in response

---

apps/api/src/controllers/v1/crawl.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
apps/api/src/scraper/WebScraper/single_url.ts

https://github.com/mendableai/firecrawl/issues/795

feat: skipTlsVerification

---

apps/api/src/controllers/auth.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/services/billing/auto_charge.ts
apps/api/src/services/billing/credit_billing.ts
apps/api/src/services/billing/issue_credits.ts
apps/api/src/services/billing/stripe.ts
apps/api/src/services/notification/email_notification.ts
apps/api/src/services/notification/notification_string.ts
apps/api/src/types.ts

see firecrawl-web#112 for change explanation.

feat: Auto Recharge Credits + Credit Packs

---

apps/api/src/controllers/v1/types.ts
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
apps/api/src/scraper/WebScraper/single_url.ts
apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/index.ts

Support for the 2 new actions

---

apps/api/src/controllers/v1/types.ts
apps/api/src/lib/entities.ts
apps/api/src/scraper/WebScraper/index.ts
apps/api/src/scraper/WebScraper/scrapers/fireEngine.ts
apps/api/src/scraper/WebScraper/single_url.ts
apps/api/src/scraper/WebScraper/utils/removeBase64Images.ts

Base64 images are huge and this is causing multiple issues

[Feat] Added remove base64 images options (true by default)

---

apps/api/src/controllers/v1/types.ts
apps/api/src/lib/entities.ts
apps/js-sdk/firecrawl/src/index.ts

Exec js - actions

---

apps/api/src/controllers/v1/types.ts
apps/api/src/lib/entities.ts
apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/index.ts

[BUG] fixes scroll action

---

apps/api/src/scraper/WebScraper/sitemap.ts

Still needs testing on whether this is stable (whether tlsclient has enough capacity to handle all the sitemaps)

fix(sitemap): scrape with tlsclient

---

apps/js-sdk/firecrawl/src/index.ts

Add mobile param for node SDK
https://www.firecrawl.dev/blog/launch-week-ii-day-6-introducing-mobile-scraping

Node SDK : Add Mobile Scraping

---

examples/hacker_news_scraper/bs4_scraper.py
examples/hacker_news_scraper/firecrawl_scraper.py
examples/hacker_news_scraper/requirements.txt

In this PR, I added a new directory to `examples`. The directory is `hacker_news_scraper` and contains three new files:
- bs4_scraper.py
- firecrawl_scraper.py
- requirements.txt
I need these two scripts for this new tutorial I am writing on scheduling web scrapers (the tutorial was approved by @ericciarla).
Cheers!

Add a new project to examples that shows how to scrape Hacker News website

---

apps/python-sdk/firecrawl/__init__.py
apps/python-sdk/firecrawl/firecrawl.py

fixed keyerror for data on sdk

---

apps/python-sdk/example.py
apps/python-sdk/firecrawl/__init__.py
apps/python-sdk/firecrawl/firecrawl.py

Fixes schema base model extract

---

apps/api/src/routes/v1.ts
apps/api/src/scraper/WebScraper/utils/blocklist.ts

Remove Block List

---

apps/api/src/scraper/scrapeURL/engines/fetch/index.ts
apps/api/src/scraper/scrapeURL/engines/fire-engine/index.ts
apps/api/src/scraper/scrapeURL/engines/index.ts
apps/api/src/scraper/scrapeURL/engines/pdf/index.ts
apps/api/src/scraper/scrapeURL/engines/playwright/index.ts
apps/api/src/scraper/scrapeURL/engines/scrapingbee/index.ts
apps/api/src/scraper/scrapeURL/index.ts

We also need to increase the timeout by default if there are actions etc, i think you do this in another place but it is not being passed here.

Timeout fixes on user defined timeouts

---

apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/sitemap.ts

- This particularly improves recursive sitemap fetching and it also checks for the base sitemap in subdomains to see if any subdomains are listed there.
@rafaelsideguide fixes the sitemap issue customer was having

Improves sitemap fetching

---

apps/api/src/scraper/scrapeURL/engines/pdf/index.ts

Future progress to be made: we should have a way of detecting how much of a PDF needs to be OCR'd, choose engine based on that. Could be done by analyzing image and text makeup of the PDF just with format parsing.

feat(scrapeURL/pdf): switch to MU (FIR-356)

---

apps/api/docker-entrypoint.sh
apps/api/package.json
apps/api/src/controllers/v1/map.ts
apps/api/src/index.ts
apps/api/src/scraper/WebScraper/sitemap.ts
apps/api/src/services/indexing/crawl-maps-index.ts
apps/api/src/services/indexing/index-worker.ts
apps/api/src/services/queue-service.ts
apps/api/src/services/queue-worker.ts

Add another queue and worker for batch insertion operations in the db such as indexing crawl_maps

(feat/index) Index/Insertion queue

---

apps/api/requests.http
apps/api/v1-openapi.json

- add cancel crawl event to requests.http

docs: update cancel crawl response

---

apps/api/src/lib/__tests__/spread-schema-objects.test.ts
apps/api/src/lib/extract/build-prompts.ts
apps/api/src/lib/extract/helpers/spread-schemas.ts
apps/api/src/lib/extract/reranker.ts
apps/api/src/lib/extract/url-processor.ts

Rerank with lower threshold + back to map if length = 0

---

apps/api/src/__tests__/snips/map.test.ts
apps/api/src/controllers/v1/map.ts
apps/api/src/controllers/v1/types.ts
apps/js-sdk/firecrawl/src/index.ts

Accidentally applied to main first, but caught it in time and reverted. Then reverted again to make this PR. Adds a timeout to map + tests.

feat(v1/map): Timeout parameter (FIR-393)

---

apps/api/src/__tests__/snips/scrape.test.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/scraper/scrapeURL/engines/fire-engine/index.ts
apps/api/src/scraper/scrapeURL/engines/fire-engine/scrape.ts
apps/js-sdk/firecrawl/src/index.ts

waiting for f-e side fixes and adding tests

feat(scrapeUrl/fire-engine): add blockAds flag (FIR-692)

---

apps/api/src/controllers/v1/types.ts
apps/api/src/lib/extract/completions/analyzeSchemaAndPrompt.ts
apps/api/src/scraper/scrapeURL/transformers/llmExtract.ts

(feat/extract) Improved completions to use model's limits

---

.github/workflows/ci.yml
apps/api/src/__tests__/snips/map.test.ts
apps/api/src/__tests__/snips/scrape.test.ts

can be merged once CI is passing (it means Tailscale works)

feat(github/ci): connect to tailscale (FIR-748)

---

CONTRIBUTING.md

A letter seemed to be forgotten

You forgot an 'e'

---

examples/gemini-2.0-crawler/gemini-2.0-crawler.py

- Added PDF and image detection for sub-links within scraped pages
- Integrated Gemini Vision API for image analysis and bounding box detection
- Added PDF text extraction using Gemini's document understanding capabilities
- Appends extracted content to main markdown for comprehensive analysis
- New helper functions:
- `is_pdf_url()` & `is_image_url()` for file type detection
- `gemini_extract_pdf_content()` for PDF text extraction
- `gemini_extract_image_data()` for image analysis and bounding boxes
- Modified `scrape_url` to include 'links' format for sub-link discovery
- Extracted content is clearly labeled with source URLs in the markdown output
This enhancement allows the crawler to discover and analyze content within PDFs and images that would otherwise be missed, providing more …

Add detection of PDF/image sub-links and extract text via Gemini

---

examples/gemini-2.0-crawler/gemini-2.0-crawler.py

- Updates logic to latest gemini api library
- Fixes extract of pdf and image urls from the scraped content

fix: update gemini library. extract pdf links from scraped content

---

apps/api/src/lib/extract/build-prompts.ts

This fixes cases where the re-ranker doesn't return all the links especially when the user request for all the links

(feat/extract) Multi-entity prompt improvements

---

.github/workflows/test-server-self-host.yml
apps/api/package.json
apps/api/pnpm-lock.yaml
apps/api/src/__tests__/snips/batch-scrape.test.ts
apps/api/src/__tests__/snips/crawl.test.ts
apps/api/src/__tests__/snips/extract.test.ts
apps/api/src/__tests__/snips/scrape.test.ts
apps/api/src/__tests__/snips/search.test.ts
apps/api/src/controllers/v1/crawl-status-ws.ts
apps/api/src/controllers/v1/crawl-status.ts
apps/api/src/controllers/v1/extract-status.ts
apps/api/src/lib/extract/completions/analyzeSchemaAndPrompt.ts
apps/api/src/lib/extract/extraction-service.ts
apps/api/src/lib/extract/index/pinecone.ts
apps/api/src/lib/llm/generate.ts
apps/api/src/lib/ranker.ts
apps/api/src/scraper/scrapeURL/engines/fire-engine/checkStatus.ts
apps/api/src/scraper/scrapeURL/engines/fire-engine/delete.ts
apps/api/src/scraper/scrapeURL/engines/fire-engine/scrape.ts
apps/api/src/scraper/scrapeURL/engines/index.ts
apps/api/src/scraper/scrapeURL/lib/fetch.ts
apps/api/src/search/fireEngine.ts
apps/api/src/search/googlesearch.ts
apps/api/src/search/index.ts
apps/api/src/services/queue-service.ts
apps/api/src/services/queue-worker.ts

Big pile of fixes for running Firecrawl on self-host, including continuous testing in a simulated self-hosted environment.

SELFHOST FIXES

---

apps/api/src/__tests__/snips/map.test.ts
apps/api/src/__tests__/snips/scrape.test.ts
apps/api/src/__tests__/snips/search.test.ts
apps/api/src/controllers/v1/map.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/scraper/WebScraper/sitemap.ts
apps/api/src/scraper/scrapeURL/engines/fetch/index.ts

Mocks out a very long running, flaky test. Should improve CI experience.

feat(map): mock support (FIR-1109)

---

.github/workflows/test-server-self-host.yml
SELF_HOST.md
apps/api/src/__tests__/snips/scrape.test.ts
apps/api/src/scraper/scrapeURL/engines/utils/safeFetch.ts
apps/playwright-service-ts/api.ts
docker-compose.yaml

Adds proxy support to `fetch` engine, and additional documentation and tests.
Fixes #1129 
Fixes #1035 
Fixes #925

feat(self-host): proxy support (FIR-1111)

---

apps/api/src/__tests__/snips/scrape.test.ts
apps/api/src/scraper/scrapeURL/engines/fetch/index.ts

fix(scrapeURL/engines/fetch): discover charset and re-decode

---

apps/api/Dockerfile

Update to latest version of tools.
Clean up
Reduce image size to 800mo (uncompressed)
See #1230

Update API Dockerfile

---

apps/api/src/services/billing/auto_charge.ts
apps/api/src/services/notification/email_notification.ts
apps/api/src/types.ts

(feat/auto-recharge) Send email suggesting an upgrade when hitting auto recharges 

---

SELF_HOST.md
apps/api/src/lib/generic-ai.ts

feat(self-host/ai): use any OpenAI-compatible API

---

.github/workflows/test-server-self-host.yml
.github/workflows/test-server.yml
apps/api/src/__tests__/snips/billing.test.ts
apps/api/src/__tests__/snips/crawl.test.ts
apps/api/src/__tests__/snips/lib.ts
apps/api/src/__tests__/snips/scrape.test.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/lib/crawl-redis.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/services/queue-worker.ts
apps/js-sdk/firecrawl/src/index.ts

- Update includes/excludes behaviour to apply to the crawl source URL too (after discovery)
- Add `regexOnFullURL` parameter

feat(crawl): includes/excludes fixes (FIR-1300)

---

apps/api/src/search/googlesearch.ts

Modified error handlers to avoid logging entire response objects that contain circular references

fix: resolve circular JSON structure error in search function

---

apps/api/src/__tests__/snips/crawl.test.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/lib/crawl-redis.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/services/queue-worker.ts
apps/js-sdk/firecrawl/src/index.ts

Customer request
Docs pair PR: https://github.com/hellofirecrawl/docs/pull/59

feat(crawl): add maxDiscoveryDepth

---

apps/api/src/routes/v1.ts

this causes a lot of customer confusion, better to just minmax it quietly

fix(v1/checkCredits): snap crawl limit to remaining credits if over without erroring out (FIR-1450)

---

apps/api/src/controllers/v1/types.ts
apps/api/src/lib/entities.ts
apps/js-sdk/firecrawl/package.json
apps/js-sdk/firecrawl/src/index.ts

waiting on f-e side implementation

feat(scrape/actions/click): add all parameter (FIR-1443)

---

apps/api/src/controllers/v1/deep-research.ts
apps/api/src/lib/deep-research/deep-research-service.ts
apps/api/src/lib/deep-research/research-manager.ts
apps/api/src/services/queue-worker.ts

The user should be able to format the final analysis however they want.

(feat/deep-research) Add Analysis Prompt

---

apps/api/src/controllers/v1/deep-research-status.ts
apps/api/src/controllers/v1/deep-research.ts
apps/api/src/lib/deep-research/deep-research-redis.ts
apps/api/src/lib/deep-research/deep-research-service.ts
apps/api/src/lib/deep-research/research-manager.ts
apps/api/src/services/queue-worker.ts
apps/js-sdk/firecrawl/src/index.ts
apps/python-sdk/firecrawl/firecrawl.py

- Added structured outputs formats
- Added system prompt
- Improved streaming of activities

(feat/deep-research) Deep Research Alpha v1 - Structured Outputs + Customizability

---

apps/api/package.json
apps/api/pnpm-lock.yaml
apps/api/src/services/logging/log_job.ts

Error-resistant so we might as well just start putting jobs in to stress test it

feat(log_job): start saving jobs to GCS

---

apps/rust-sdk/Cargo.lock
apps/rust-sdk/Cargo.toml
apps/rust-sdk/examples/batch_scrape_example.rs
apps/rust-sdk/examples/cancel_crawl_example.rs
apps/rust-sdk/examples/check_crawl_errors_example.rs
apps/rust-sdk/examples/example.rs
apps/rust-sdk/examples/extract_example.rs
apps/rust-sdk/examples/llmstxt_example.rs
apps/rust-sdk/examples/search_example.rs
apps/rust-sdk/src/batch_scrape.rs
apps/rust-sdk/src/crawl.rs
apps/rust-sdk/src/document.rs
apps/rust-sdk/src/error.rs
apps/rust-sdk/src/extract.rs
apps/rust-sdk/src/lib.rs
apps/rust-sdk/src/llmstxt.rs
apps/rust-sdk/src/map.rs
apps/rust-sdk/src/scrape.rs
apps/rust-sdk/src/search.rs
apps/rust-sdk/tests/e2e_with_auth.rs

This pull request introduces several new features and improvements to the `firecrawl` Rust SDK. It adds support for batch scraping, crawl job cancellation, error checking, LLMs.txt generation, and search functionality. Additionally, it includes various example programs demonstrating the usage of these new features.
- Add async batch scrape URLs functionality
- Implement monitoring and error checking for batch scrapes
- Introduce cancel crawl and crawl errors checking
- Adds llmstxt generation with async status checks
- Implement search functionality with various example queries
- Introduce extract functionality with schema support
- Include multiple examples for SDK features and usage
I wanted to integrate some of the new awesome features of firecrawl ❤️ in rust and enable try batch …

feat(rust): update rust sdk to support new features

---

apps/api/src/controllers/v1/scrape.ts
apps/api/src/services/queue-worker.ts

fix(queue-worker, scrape): stealth proxy pricing change (FIR-1847)

---

apps/api/src/controllers/auth.ts
apps/api/src/controllers/v0/crawl.ts
apps/api/src/controllers/v0/crawlPreview.ts
apps/api/src/controllers/v0/scrape.ts
apps/api/src/controllers/v0/search.ts
apps/api/src/controllers/v1/batch-scrape.ts
apps/api/src/controllers/v1/crawl.ts
apps/api/src/controllers/v1/extract.ts
apps/api/src/controllers/v1/map.ts
apps/api/src/controllers/v1/search.ts
apps/api/src/controllers/v1/types.ts
apps/api/src/lib/crawl-redis.ts
apps/api/src/lib/deep-research/deep-research-service.ts
apps/api/src/lib/extract/extraction-service.ts
apps/api/src/lib/extract/fire-0/extraction-service-f0.ts
apps/api/src/lib/extract/fire-0/reranker-f0.ts
apps/api/src/lib/extract/fire-0/url-processor-f0.ts
apps/api/src/lib/extract/reranker.ts
apps/api/src/lib/extract/url-processor.ts
apps/api/src/lib/generate-llmstxt/generate-llmstxt-service.ts
apps/api/src/routes/v1.ts
apps/api/src/scraper/WebScraper/utils/__tests__/blocklist.test.ts
apps/api/src/scraper/WebScraper/utils/blocklist.ts
apps/api/src/services/queue-worker.ts

ACUC change is in Linear ticket

feat(acuc): propagate team flags (FIR-1879)

---

apps/api/src/lib/extract/fire-0/extraction-service-f0.ts

Log errors from old Extract like we do for new Extract. Good for support.

feat(api/extract/fire-0): error logging (FIR-1971)

---

apps/api/src/lib/extract/extraction-service.ts
apps/api/src/lib/extract/fire-0/extraction-service-f0.ts
apps/api/src/lib/generate-llmstxt/generate-llmstxt-service.ts

Helps with debugging billing things.

feat(api/extract): show extract as origin for scrapes originating from it (FIR-2061)

---

apps/api/src/scraper/scrapeURL/lib/fetch.ts

Avoid logging huge contents, like PDF base64.

fix(robustFetch): selective logging (FIR-2072)

---

apps/api/src/controllers/v0/admin/cclog.ts
apps/api/src/routes/admin.ts

This endpoint scans the Redis for currently active concurrency queues, and appends details about them to the concurrency_log table. The endpoint will be called by a Supabase Cron.

feat(concurrency-log): add cclog endpoint (FIR-2067)

---

apps/api/src/controllers/v0/admin/cclog.ts
apps/api/src/controllers/v0/crawl-cancel.ts
apps/api/src/controllers/v0/crawl-status.ts
apps/api/src/controllers/v0/crawl.ts
apps/api/src/controllers/v0/keyAuth.ts
apps/api/src/controllers/v0/scrape.ts
apps/api/src/controllers/v0/search.ts
apps/api/src/controllers/v1/concurrency-check.ts
apps/api/src/controllers/v1/crawl-errors.ts
apps/api/src/lib/concurrency-limit.ts
apps/api/src/lib/crawl-redis.ts
apps/api/src/lib/deep-research/deep-research-redis.ts
apps/api/src/lib/extract/extract-redis.ts
apps/api/src/lib/generate-llmstxt/generate-llmstxt-redis.ts
apps/api/src/lib/job-priority.ts
apps/api/src/scraper/WebScraper/crawler.ts
apps/api/src/services/notification/email_notification.ts
apps/api/src/services/queue-service.ts
apps/api/src/services/queue-worker.ts
apps/api/src/services/redis.ts

feat(apps/api): add support for a separate, non-eviction Redis

---

.github/workflows/deploy-playwright.yml
docker-compose.yaml

feat(selfhost): deploy a playwright image

---

README.md

fix(readme): clarify that scrape_options must be a ScrapeOptions instance crawl_url and typo fixes

---

apps/api/src/controllers/v1/map.ts
apps/api/src/controllers/v1/search.ts
apps/api/src/lib/deep-research/deep-research-service.ts
apps/api/src/lib/generate-llmstxt/generate-llmstxt-service.ts
apps/api/src/services/logging/log_job.ts
apps/api/src/services/queue-worker.ts

also a bit of logging improvement for logJob

feat: add credits_billed everywhere (FIR-2286)

---

apps/api/src/index.ts

Replace verbose JSON stringification of errors with passing the error
object directly to the logger. This change enhances error logging by
preserving error details like message and stack trace in a structured
format, improving readability and debugging.

fix(api): improve error logging with structured error object

---

apps/api/src/index.ts

Update error handler to use RequestWithMaybeACUC type, allowing
access to optional ACUC properties on the request object. Include
team_id from ACUC in error logging to improve context for debugging.

fix(api): enhance error handler with optional ACUC data

---

apps/api/src/lib/gcs-jobs.ts

Fixes performance issues during local development

fix(api): instantiate Storage only once

---

apps/api/src/lib/concurrency-limit.ts

not that serious until i > 15, which may indicate infinite looping

fix(concurrency-limit): overlogging

---

apps/api/src/controllers/v1/types.ts
apps/api/src/scraper/scrapeURL/engines/fire-engine/index.ts
apps/js-sdk/firecrawl/src/index.ts
apps/python-sdk/firecrawl/firecrawl.py

You can now specify screenshot quality throught the screenshot action

feat: Screenshot quality

---

apps/api/src/lib/deep-research/deep-research-service.ts

fix(api/deep-research): bad default values leading to bug on self-host

---

apps/api/sharedLibs/html-transformer/src/lib.rs

fix(html-transformer): check base tag when resolving relative URLs

---

apps/api/sharedLibs/html-transformer/src/lib.rs
apps/api/src/lib/html-transformer.ts

bad srcset handling + bad grapheme splitting

fix(api/html-transformer): stop panicing on arabic sites

---

apps/api/src/controllers/v1/search.ts

shove it into crawlerOptions in the DB

feat(search): improve param logging

---

apps/api/src/scraper/scrapeURL/engines/index.ts

quick n' dirty fix before we get a matcher

fix(scrapeURL/index): exclude waitfor

---

apps/api/src/controllers/v1/crawl-status.ts

Reverts mendableai/firecrawl#1716

Revert "Add temporary exception for Faire team ID to bypass job expiration"

---

apps/api/src/services/queue-worker.ts

This PR fixes the `ERR_WORKER_INVALID_EXEC_ARGV` error that occurs when BullMQ tries to create worker threads with the `--max-old-space-size` flag.
When the main process is started with `--max-old-space-size=8192` (as configured in docker-entrypoint.sh), this flag is passed to worker threads through `process.execArgv`. However, worker threads have restrictions on which flags they can accept, and `--max-old-space-size` is not allowed for worker threads, causing the error:
```
Error [ERR_WORKER_INVALID_EXEC_ARGV]: Initiated Worker with invalid execArgv flags: --max-old-space-size=8192
```
The fix filters out the invalid flag and properly sets memory limits using the worker threads API:
- Extracts the memory size value from the `--max-old-space-size` flag
- Filters out the flag from …

Fix: Handle --max-old-space-size flag for worker threads

---

apps/api/package.json
apps/api/src/harness.ts
examples/kubernetes/firecrawl-helm/templates/deployment.yaml

prevents rebuilds of natives etc every time files are changed (use `dev` or `start:production` script)

Perform watching inside of harness (ENG-3514)

---

CONTRIBUTING.md

Fixes typos and missing punctuation in CONTRIBUTING.md
- Fixes a typo "gettin" corrected to "getting"
- Adds a missing apostrophe for won't 
- Removes extra space before an ending parenthesis

docs: fix typo and punctuation in CONTRIBUTING.md
