firecrawl/firecrawl

apps/playwright-service/main.py
Best practise to close contexts before closing the browser. 
```
This will ensure the `context` is closed gracefully and any artifacts—like HARs
and videos—are fully flushed and saved.
```
=> chore: add context.close

apps/api/src/__tests__/e2e_noAuth/index.test.ts, apps/api/src/__tests__/e2e_withAuth/index.test.ts, apps/api/src/controllers/crawl.ts, apps/api/src/controllers/crawlPreview.ts, apps/api/src/controllers/scrape.ts, apps/api/src/scraper/WebScraper/utils/blocklist.ts
=> [Feat] Added blocklist for social media urls

apps/api/.env.example, apps/api/src/__tests__/e2e_noAuth/index.test.ts, apps/api/src/__tests__/e2e_withAuth/index.test.ts, apps/api/src/controllers/search.ts, apps/api/src/lib/entities.ts, apps/api/src/routes/v0.ts, apps/api/src/scraper/WebScraper/single_url.ts, apps/api/src/scraper/WebScraper/utils/metadata.ts, apps/api/src/search/googlesearch.ts, apps/api/src/search/index.ts, apps/api/src/search/serper.ts, apps/api/src/types.ts
MVP for the /search endpoint. 
Introduces a serp + firecrawl experience. Allows user to search a query and get the top n results in google. **It will also return the n page contents in markdown along with the page metadata**. It is optimized for speed. Currently search is around ~10-12s depending on the query with benchmarks of 2s for the initial search itself - very comparable to other search apis. Still lots of room for improvements  ( n defined by limit/default 7 )
POST v0/search
```
{
query: "what is a coconut?",
searchOptions:{
limit: 5 // max 20 for now
}
}
```
Pending for release:
=> [Feat:mvp] Search Endpoint => serp api + firecrawl => 🔥 🔍 

apps/api/fly.toml, apps/api/src/__tests__/e2e_withAuth/index.test.ts, apps/api/src/controllers/crawl-cancel.ts, apps/api/src/controllers/crawl.ts, apps/api/src/lib/entities.ts, apps/api/src/main/runWebScraper.ts, apps/api/src/routes/v0.ts, apps/api/src/scraper/WebScraper/index.ts, apps/api/src/services/logging/crawl_log.ts
closes #106
Notes: Bull doesnt allow to cancel active jobs.
Design decision: we mark the job as failed when someone cancels, and we stop the scraping process (which is the actual expensive process). We bill them as soon as they cancel, even if some promises are not resolved resulting in them getting more from what they paid (totally cool!)
I think this works fairly well for now. @rafaelsideguide would love a look over.
=> Cancel Job Route

apps/python-sdk/firecrawl/firecrawl.py
Allows python sdk to be used with local installs.
Add optional parameter for the class, and defers to environment variable FIRECRAWL_API_URL if set.
=> Allow override of API URL

apps/api/.env.example, apps/playwright-service/main.py, docker-compose.yaml
Updated environment variables and application settings to include proxy configurations and media blocking option. The proxy settings allow users to use a proxy service, while the media blocking is an optional feature that can help save bandwidth. Changes have been made in the .env.example, docker-compose.yaml, and main.py files.
=> [Feat] Added proxy and media blocking support for Playwright

apps/api/openapi.json, apps/api/src/__tests__/e2e_withAuth/index.test.ts, apps/api/src/controllers/scrape.ts, apps/api/src/lib/entities.ts, apps/api/src/scraper/WebScraper/single_url.ts
closes #199 allowing users to set a wait param to wait x ms after the page load to grab its content in fire-engine and playwright.
=> Allow users to manually set the waitFor param on /scrape

.github/scripts/check_version_has_incremented.py, .github/scripts/requirements.txt
@rafaelsideguide 
This pull request adds a new script to check if the version of a local package has been incremented compared to the published version on PyPI (for Python packages) or npm (for JavaScript packages). The script supports both Python and JavaScript packages and can be executed from the command line or as part of a github action.
**Script Overview:**
The script retrieves the current version of the package from the local filesystem.
For Python packages, it fetches the version from __init__.py.
For JavaScript packages, it fetches the version from package.json.
It then retrieves the latest published version from PyPI (for Python) or npm (for JavaScript).
The script compares the local version with the published version and prints true if the local version is greater (indicating …
=> Script to check local vs published versions of sdk packages

SELF_HOST.md, examples/k8n/README.md, examples/k8n/api.yaml, examples/k8n/configmap.yaml, examples/k8n/playwright-service.yaml, examples/k8n/redis.yaml, examples/k8n/secret.yaml, examples/k8n/worker.yaml
Added new files for setting up Firecrawl on a Kubernetes Cluster. The files include Kubernetes manifests for deploying API, worker, playwright service, and Redis with associated ConfigMap and Secret associated resources. Also, updated the self-host documentation to include instructions for Kubernetes deployment.
=> Add Kubernetes configuration for Firecrawl deployment

apps/api/.env.example, apps/api/src/services/webhook.ts
This commit introduces the capability of using a Self-Hosted Webhook URL. The application now checks for a self-hosted URL before querying the database for the webhook settings. If a Self-Hosted Webhook URL is set in the environment variables, it will be used directly, diminishing unnecessary database queries.
=> Add support for Self-Hosted Webhook URL Usage and added project_id into the webhook payload

apps/api/src/lib/entities.ts, apps/api/src/scraper/WebScraper/crawler.ts, apps/api/src/scraper/WebScraper/index.ts, apps/api/src/scraper/WebScraper/sitemap.ts
Fixes #257
Introduces a ignoreSitemap for crawlerOptions, that bypasses the sitemap when crawling.
With this change, we also introduce a wider crawling range by excluding the `includes` from the crawler itself. That way we don't restrict the crawler too much as later we filter that out any way.
=> ignoreSitemap feature, pageOptions now respected in the initial crawl as well

apps/api/src/__tests__/e2e_withAuth/index.test.ts, apps/api/src/scraper/WebScraper/single_url.ts, apps/api/src/scraper/WebScraper/utils/__tests__/removeUnwantedElements.test.ts, apps/api/src/scraper/WebScraper/utils/removeUnwantedElements.ts
Added support for regex removeTags, starting and ending with "*"
Example:
```
"removeTags": [
"*cmplz*",
"*menu*",
"*footer*",
"*header*",
"*nav*",
"*follow-links*",
"*privacy*",
"*cookie*",
"*popup*",
"*overlay*",
"*developed*",
"*cms*"
]
```
=> [Feat] Added support for RegEx in removeTags

apps/api/package.json, apps/api/src/scraper/WebScraper/single_url.ts
Closes #291 
Tested with `requests.http`:
```
POST http://localhost:3002/v0/scrape HTTP/1.1
Authorization: Bearer fc-<YOUR-KEY-HERE>
content-type: application/json
{
"url":"mendable.ai",
"pageOptions": {
"includeHtml": true,
"onlyMainContent": true
}
}
```
the `html` should **not** contain "introducing" (from Firecrawl banner)
=> [Bug] Fixed includeHTML to use cleanedHtml as response

apps/api/src/search/googlesearch.ts
I tried to use /search without Serp in my self-hosted app, and there was the result of the request:
`
curl -X POST http://localhost:3002/v0/search \
-H 'Content-Type: application/json' \
-d '{
"query": "What is Mendable?"
}'
`
This error only happens when the search term is a sentence.
In my fix, I pass the **term** without URLencode as this is apparently not as necessary when it is sent by params via axios.
so there are no problems with special characters after this change:
`
curl -X POST http://localhost:3002/v0/search \
-H 'Content-Type: application/json' \
-d '{
"query": "Como funciona validação cruzada em LLMs?"
}'
`
=> fix multi-word search term issue: /search (w/o Serp)

apps/api/src/services/webhook.ts, docker-compose.yaml
1. Fixes missing env var mapping in docker-compose.yml
2. Allows for connection to local machine from docker-compose network
3. Rudimentary jobId templating for webhook URL (self-hosted only of course)
=> Self-hosting quality of life fixes

apps/api/src/controllers/crawl-status.ts, apps/api/src/controllers/status.ts, apps/api/src/main/runWebScraper.ts, apps/api/src/services/logging/log_job.ts
Trying self hosting with `USE_DB_AUTHENTICATION=false`, some API endpints still tries to use Supabase and that seems blocking to get responses.
```
$ diff apps/api/.env.example .env
5c5
< REDIS_URL=redis://localhost:6379
---
> REDIS_URL=redis://redis:6379
9c9
< USE_DB_AUTHENTICATION=true
---
> USE_DB_AUTHENTICATION=false
$ docker compose up
```
```
$ curl -X POST http://localhost:3002/v0/crawl \
-H 'Content-Type: application/json' \
-d '{"url": "https://mendable.ai"}'
{"jobId":"55a746a8-2c99-4066-853a-b362b2f298ba"}
```
```
$ curl -X GET http://localhost:3002/v0/crawl/status/55a746a8-2c99-4066-853a-b362b2f298ba
{"error":"Supabase client is not configured."}
```
console shows:
```
api-1                 | Attempted to access Supabase client when it's not configured.
api-1                 | …
```
=> Fix USE_DB_AUTHENTICATION checks for self-host

apps/js-sdk/firecrawl/build/index.js, apps/js-sdk/firecrawl/package-lock.json, apps/js-sdk/firecrawl/package.json, apps/js-sdk/firecrawl/src/__tests__/e2e_withAuth/index.test.ts, apps/js-sdk/firecrawl/src/index.ts
issue #387 
Ideally, I think these would be marked as required fields, but due to their instability in my local testing (often resolving to `undefined`), I've marked them all as optional, which I think makes sense for backward compatibility.
=> [Feat] Pass along current, total, current_step, and current_url in js sdk

apps/api/src/lib/entities.ts, apps/api/src/scraper/WebScraper/__tests__/single_url.test.ts, apps/api/src/scraper/WebScraper/single_url.ts, apps/api/src/scraper/WebScraper/utils/utils.ts
For issue #421. I just extract the links from the HTML then return them as the linksOnPageParameter.
I thought about making this optional, but I couldn't see any downside to just including them. Might adding an optional parameter just add complexity?
Would love your take @rafaelsideguide @nickscamara 
Either way, the customer needs this by EOW lets get it merged :)
=> Caleb: Return a list of links on a page by default

apps/api/src/scraper/WebScraper/utils/replacePaths.ts
After SSH-ing into a frozen Fly machine with CPU utilization on 100%, I noticed that the process using the most CPU was Node itself.
After putting Node into debugging mode, attaching the monitor, and pausing the process, it was stuck on a regex in `replacePaths`.
I dumped the document's content and I was able to reproduce the issue locally. I consulted with @rafaelsideguide to replace the problematic regex with something that still worked the same, and I tested the new regex locally.
=> fix(WebScraper): infinite regex leading to fly.io instance hangs

apps/api/src/scraper/WebScraper/crawler.ts
malformed sitemaps (example `lunit.io/en/`, get's `/` as sitemap url which causes server error)
=> Added regex for links in sitemap

apps/api/src/scraper/WebScraper/crawler.ts, apps/api/src/scraper/WebScraper/sitemap.ts
First axios request gets back 200 but second returns 403 error on `getLinksFromSitemap` function. Changing to `fire-engine` for solves this issue but definitely not the best solution for self-host. Added also a check for FIRE_ENGINE_BETA_URL on `getLinksFromSitemap`.
Closes #477
=> [Bug] Nested sitemaps

apps/api/src/controllers/auth.ts, apps/api/src/index.ts, apps/api/src/services/billing/credit_billing.ts, apps/api/src/services/redlock.ts, apps/js-sdk/firecrawl/build/cjs/index.js, apps/js-sdk/firecrawl/package-lock.json, apps/js-sdk/firecrawl/package.json
When a user receives a 429, we cache their team_id / price_id preventing multiple requests to go through the db.
Pros:
- Mitigates db issues where overloads giving users 401 errors
Cons:
- Small added latency to users doing mulitple requests per s when hitting 429s
- If they upgrade the plan during the cache expiration time, it wont upgrade them immediately. Cache will need to expire first (5 min TTL)
=> Redlock cache in auth

apps/api/.env.example
Self-host docs suggest using .env.example as a base. However, Docker doesn't respect end-of-line comments. It sets the comment as the actual value of the variable, leading to invalid behavior. This fix prevents that.
=> Self-host fix: Moving comments of .env.example values from end-of-line to above-line.

apps/go-sdk/README.md, apps/go-sdk/examples/example.go, apps/go-sdk/examples/go.mod, apps/go-sdk/go.mod
This PR fixes go-sdk module name, so it matches with the project layout
README and example are also updated with new module name
Please reference the issue this PR will close: #533  
Firecrawl go-sdk is added in this PR: #497
=> fix: go-sdk module name

SELF_HOST.md
I was attempting self-hosting by referring to the following document, and I noticed that the URL path was outdated, so I fixed it.
- https://github.com/mendableai/firecrawl/blob/v1.0.0/SELF_HOST.md
I have compared it with the official documentation at https://docs.firecrawl.dev/api-reference/endpoint/crawl-post, and the issue has been corrected.
=> [Docs] upgraded the path of the self-hosted documentation URL to `/v1`.

apps/python-sdk/firecrawl/firecrawl.py, apps/python-sdk/pyproject.toml, apps/python-sdk/requirements.txt
tested websocket with example.py without asyncio and it works with no problem.
Closes #644
=> fix(py-sdk): removed asyncio package

apps/python-sdk/firecrawl/firecrawl.py
Remove the print statement in map_url, which could be confusing when some client code has print statements for debugging.
=> Remove print statement in map

README.md
Adding `wait_until_done` parameter to the `crawl_url` function will throw a TypeError: FirecrawlApp.crawl_url() got an unexpected keyword argument 'wait_until_done'.
=> Docs: Remove wait_until_done from python-sdk example

apps/api/src/controllers/v1/types.ts
example: https://www.granitecreek.com?asljhda=akjshd
closes #710
=> [BUG] Fixed URLs with params

apps/js-sdk/firecrawl/src/index.ts
Closes #758 
Previously the error would look like:
```
.../firecrawl/apps/js-sdk/node_modules/firecrawl/build/esm/index.js:67
throw new Error(error.message);
^
Error: Request failed with status code 402
at FirecrawlApp.scrapeUrl (.../firecrawl/apps/js-sdk/node_modules/firecrawl/build/esm/index.js:67:19)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at main (.../firecrawl/apps/js-sdk/example.ts:8:24)
Node.js v20.9.0
```
Now it looks like:
```bash
.../firecrawl/apps/js-sdk/firecrawl/src/index.ts:571
throw new FirecrawlError(
^
FirecrawlError: Failed to scrape URL. Status code: 402. Error: Insufficient credits. For more credits, you can upgrade your plan at https://firecrawl.dev/pricing.
at FirecrawlApp.handleError …
```
=> [BUG] Fixed missing error handling in JS-SDK

apps/api/src/controllers/v1/crawl-status.ts
I found a crawl that got stuck on "scraping" status for hours (`url: rospa.com`). This fixes it.
=> [BUG] filters failed and unknown jobs now

README.md
When we use `as`, typescript does not validate the types properly in scenarios like the typescript example. The `satisfies` operator is stricter and **does** validate the types, preventing misuse like such:
Using blank object
```ts
interface CrawlParams {
required: boolean
}
// This is valid
const config = {} as CrawlParams
// this is invalid because 'required' field is missing
const config = {} satisfies CrawlParams
// ^ Type '{}' does not satisfy the expected type 'CrawlParams'. Property 'required' is missing in type '{}' but required in type 'CrawlParams'.
```
=> chore(README.md): use `satisfies` instead of `as` for ts example

apps/api/src/scraper/WebScraper/utils/utils.ts
Customer found a bug while scraping [sentientsight.com](http://sentientsight.com/):
```
{
"type": "error",
"stack": "TypeError: Invalid URL\n at new URL (node:internal/url:806:29)\n at Element.<anonymous> (/app/dist/src/scraper/WebScraper/utils/utils.js:67:28)\n at LoadedCheerio.each (/app/node_modules/.pnpm/cheerio@1.0.0-rc.12/node_modules/cheerio/lib/api/traversing.js:519:26)\n at extractLinks (/app/dist/src/scraper/WebScraper/utils/utils.js:58:12)\n at scrapSingleUrl
...
}
```
This fixes it.
=> [BUG] Added trycatch and removed redundancy

apps/api/src/controllers/v1/types.ts, apps/api/src/lib/crawl-redis.test.ts, apps/api/src/lib/crawl-redis.ts, apps/api/src/services/queue-worker.ts, apps/js-sdk/firecrawl/src/index.ts
This PR adds some important features:
- If a crawl's scrape was redirected, the target URL is also locked, preventing it from being scraped again later.
- `lockURL` now generates similar URLs that will presumably return the same content, and it will lock all of them, preventing the same content from being scraped twice. This can be disabled with the `deduplicateSimilarURLs` crawl parameter (on by default).
- Added missing parameters to the JS SDK.
=> feat(crawl): Similar URL deduplication

apps/api/src/controllers/v0/crawl.ts, apps/api/src/controllers/v1/batch-scrape.ts, apps/api/src/controllers/v1/crawl.ts, apps/api/src/controllers/v1/types.ts, apps/api/src/lib/crawl-redis.ts, apps/api/src/services/queue-worker.ts, apps/js-sdk/firecrawl/src/index.ts
Setting `ignoreQueryParameters` to false (true by default which retains old logic) will treat changes to the query parameters of the URL as expected to return different content.
=> feat(crawl): add parameter to treat differing query parameters as different URLs

apps/api/src/lib/crawl-redis.ts, apps/api/src/scraper/WebScraper/crawler.ts, apps/api/src/services/queue-worker.ts
Fixes #821 
Went for an easier fix. Just fixes the logic when adding relative URLs to the crawl from the site content. Was basing the `new URL` off of the wrong base URL.
=> fix(crawler): relative URL handling on non-start pages

apps/api/logview.js, apps/api/src/controllers/v0/scrape.ts, apps/api/src/controllers/v1/extract.ts, apps/api/src/controllers/v1/types.ts, apps/api/src/main/runWebScraper.ts, apps/api/src/scraper/scrapeURL/lib/extractMetadata.ts, apps/api/src/types.ts
Restructured runWebScraper a little to make this work. Also needed some typing changes in some other changes -- fixed Document metadata to have statusCode always defined, since it always is.
=> feat(runWebScraper): retry a scrape max 3 times in a crawl if the status code is failure (FIR-293)

apps/api/src/controllers/v1/types.ts, apps/api/src/lib/cache.ts, apps/api/src/scraper/scrapeURL/index.ts
basically moves `internalOptions.v0UseFastMode` to `scrapeOptions`
=> feat: add scrapeOptions.fastMode (FIR-288)

apps/playwright-service-ts/api.ts
The Playwright microservice was returning `pageError: false` for successful scrapes, but the main API expects `pageError` to be either a string or undefined (as defined by the Zod schema). This schema mismatch caused Playwright result parsing to fail silently, making the main API fall back to fetch even when Playwright successfully scraped the page.
Modified the Playwright service response to:
1. Return `undefined` instead of `false` for successful scrapes (status code 200)
2. Only include `pageError` in the response when there is an actual error
3. Use spread operator to conditionally include pageError: `...(pageError && { pageError })`
- Tested with local setup running both services
- Successfully scraped test URLs with Playwright without falling back to fetch
- Confirmed proper error …
=> fix: adjust Playwright service response to match API schema expectations

apps/api/src/scraper/scrapeURL/lib/extractMetadata.ts
Removes extra text in title metadata. Example: "https://help.dropbox.com/storage-space/account-space-left" previously had the metadata.title = "How to check how much Dropbox storage space is left - Dropbox HelpClearSearchLoadingClearSearchLoadingperson iconhighlighter iconhighlighter icon", now it's "How to check how much Dropbox storage space is left - Dropbox Help"
=> [BUG] fixed title extra info

apps/js-sdk/firecrawl/src/__tests__/index.test.ts, apps/js-sdk/firecrawl/src/__tests__/v1/e2e_withAuth/index.test.ts, apps/js-sdk/firecrawl/src/index.ts
Fixes: https://github.com/mendableai/firecrawl/issues/961
Description:
- Updates SDK to only require API key validation for cloud service (api.firecrawl.dev)
- Allows SDK initialization without API key for self-hosted instances
- Updates test suite to handle both cloud and self-hosted scenarios
=> feat(js-sdk): Make API key optional for self-hosted instances

CONTRIBUTING.md
Fixes: #1004
Add Docker Compose as an alternative setup method in CONTRIBUTING.md to simplify the local development process. This provides developers with an alternative choice:
- Quick setup using Docker Compose
The change maintains all existing documentation while adding the simpler Docker Compose option.
=> docs(CONTRIBUTING.md): Add Docker Compose setup instructions

apps/js-sdk/firecrawl/package.json, apps/js-sdk/firecrawl/src/index.ts
Customer found the following error when 502
```bash
Error: TypeError: Cannot use 'in' operator to search for 'next' in
2024-12-11T08:38:12.249Z
<html><head>
2024-12-11T08:38:12.249Z
<meta http-equiv="content-type" content="text/html;charset=utf-8">
2024-12-11T08:38:12.249Z
<title>502 Server Error</title>
2024-12-11T08:38:12.249Z
</head>
2024-12-11T08:38:12.249Z
<body text=#000000 bgcolor=#ffffff>
2024-12-11T08:38:12.249Z
<h1>Error: Server Error</h1>
2024-12-11T08:38:12.249Z
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
2024-12-11T08:38:12.249Z
<h2></h2>
2024-12-11T08:38:12.249Z
</body></html>
2024-12-11T08:38:12.249Z
at FirecrawlApp.monitorJobStatus (/usr/src/app/node_modules/@mendable/firecrawl-js/dist/index.cjs:54 …
```
=> [bug/JS-SDK]Added check for object and trycatch as workaround for 502s

apps/api/v1-openapi.json
Fixes: #1000
Add credit usage API docs
This PR adds docs for the `/credit-usage` endpoint to the `v1-openapi.json` file. The docs includes:
*   Endpoint definition with GET method.
*   Bearer authentication requirement.
*   Success response schema with remaining credits.
*   Error responses for 404 and 500 status codes.
This change makes sure that the API docs reflect the functionality of the credit usage endpoint
=> docs(credit-usage-api): add new endpoint documentation for credit usage

apps/python-sdk/firecrawl/__tests__/v1/e2e_withAuth/test.py, apps/python-sdk/firecrawl/firecrawl.py, apps/python-sdk/pyproject.toml, apps/python-sdk/requirements.txt
Fixes: https://github.com/mendableai/firecrawl/issues/961
Description:
Make API key validation conditional based on API URL. API key is now only required when using cloud service (api.firecrawl.dev). This allows easier self-hosting by removing API key requirement for local/self-hosted instances.
Changes:
- Modified API key validation logic in FirecrawlApp
- Updated tests to handle both cloud and self-hosted scenarios
- Added missing test dependencies
=> feat(python-sdk): Make API key optional for self-hosted instances

apps/api/src/scraper/scrapeURL/lib/extractMetadata.ts
Hello,
We cannot simply select the element using `'link[rel="icon"]'` because some websites (e.g., [_https://www.mendable.ai/_](https://www.mendable.ai/)) use tags like `<link href="/favicon.ico" rel="shortcut icon">` where the `rel` property includes additional details. To address this, we filter all `<link>` tags that contain `icon` in their `rel` attribute and select the first matching one.
----
**Preview without `favicon`**
----
**Preview with `favicon` where `rel="icon"`**
----
**Preview with `favicon` where `rel="whatever-value icon"`**
=> [FIR-37] feat: extract and return favicon URL during scraping

apps/api/src/lib/withAuth.ts
I am using API `/v0/crawl` with the limit=10 setting, but this setting does not take effect. 
After some investigation, I found that in code https://github.com/mendableai/firecrawl/blob/c911aad228ebb76384833e8e95e2a074f9d78030/apps/api/src/controllers/v0/crawl.ts#L82-L97
`remainingCredits` returns undefined, which causes `Math.min(remainingCredits, crawlerOptions.limit)` to return a `NaN`, resulting in the limit parameter not being effective.
=> fix: merge mock success data

SELF_HOST.md, apps/rust-sdk/src/error.rs, apps/rust-sdk/src/lib.rs, apps/rust-sdk/tests/e2e_with_auth.rs
Fixes: https://github.com/mendableai/firecrawl/issues/961
Description:
Modified the Rust SDK to make API keys optional for self-hosted instances while keeping them mandatory for cloud service (api.firecrawl.dev). 
Added tests to verify this behavior. 
This change aligns with documentation update regarding API key requirements.
=> feat(rust-sdk): Make API key optional for self-hosted instances

apps/playwright-service-ts/api.ts, apps/playwright-service-ts/package.json
The `random-useragent` package (https://github.com/skratchdot/random-useragent) hasn't been updated for three years and in it repo user agents set manually via json file, therefore they all are easily detected (because old).
so it would be better to add a new modern package that generates different actual user agents daily (https://github.com/intoli/user-agents)
=> feat: use new random user agent instead of the old one

apps/js-sdk/firecrawl/src/index.ts
Fixed CrawlWatcher creating WebSocket using standard http url from base app.
=> Fix bad WebSocket URL in CrawlWatcher

apps/api/src/__tests__/snips/mocks/mocking-works-properly.json, apps/api/src/__tests__/snips/scrape.test.ts, apps/api/src/controllers/v1/types.ts, apps/api/src/scraper/scrapeURL/lib/fetch.ts, apps/api/src/scraper/scrapeURL/lib/mock.ts
There is a fire-engine-side PR for implementing this. Tests have been added.
First, the F-E change needs to be merged, then this one.
=> fix(scrapeURL/fire-engine): default to separate US-generic proxy list if no location is specified (FIR-728)

apps/api/src/controllers/v0/crawl-cancel.ts, apps/api/src/controllers/v0/crawl-status.ts, apps/api/src/controllers/v0/crawl.ts, apps/api/src/controllers/v0/keyAuth.ts, apps/api/src/controllers/v0/scrape.ts, apps/api/src/controllers/v0/search.ts
Prerequisite of sending out e-mails. I don't think this will cause too much memory pressure on the Redis side -- it's a set, so we're not storing duplicates, and it's all just UUIDs.
=> feat(v0): store v0 users (team ID) in Redis for collection (FIR-698)

apps/api/Dockerfile, apps/api/docker-entrypoint.sh, docker-compose.yaml
This is a set of changes that addressed the corepack issue and some additional issues with running the docker compose file in my self-hosted environment.
See issue: #1126 
I fixed the corepack issue by following this approach:
* [pnpm corepack fix suggestion](https://github.com/pnpm/pnpm/issues/9029#issuecomment-2631400936)
After fixing the corepack issue, I was left with this error:
* `ulimit: open files: cannot modify limit: Operation not permitted`
* In my research, you cannot set the ulimit from the docker entrypoint script.
* You need to set it as part of running the image like `docker run --ulimit nofile=65535:65535 your-image` or in the docker compose file as i have implemented
=> Fix corepack and self hosting setup

apps/api/src/lib/crawl-redis.test.ts, apps/api/src/lib/crawl-redis.ts
Doesn't scrape the same URL twice if it also discovers the same thing with `/index.html` or `/index.php` on the end.
=> fix(crawl-redis/generateURLPermutations): dedupe index.html/index.php/slash/bare URL ends (FIR-827)

apps/api/sharedLibs/html-transformer/src/lib.rs
Correct the parameter type to use libc::c_char for better type consistency 
Fixes #1152
=> fix(html-transformer): Update free_string function parameter type

apps/api/src/services/queue-worker.ts
Fixes bad activity log document count for crawls with failed jobs, causing customer confusion wrt limits not working.
=> fix(queue-worker/crawl): only report successful page count in num_docs (FIR-960)

apps/api/src/scraper/WebScraper/crawler.ts
according to ： https://developer.mozilla.org/en-US/docs/Web/API/URL/URL 
> new URL(url, base)
[base](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL#base) Optional
A string representing the base URL to use in cases where url is a relative reference. If not specified, it defaults to undefined.
eg: 
* pageUrl = `http://example.com/a/b/c/d.html `
* tag : `<a herf="../e.html"></a>`
correct: `new URL('../e.html','http://example.com/a/b/c/d.html')`
incorrect: `new URL('../e.html','http://example.com')`
=> fix: relative url 2 full url use error base url

apps/api/src/controllers/v1/crawl-errors.ts, apps/api/src/controllers/v1/crawl-status-ws.ts, apps/api/src/controllers/v1/crawl-status.ts, apps/api/src/lib/concurrency-limit.ts, apps/api/src/lib/crawl-redis.ts
Fixes a multitude of annoying bugs, including:
- Crawls that have all their pending jobs in the concurrency queue are considered "completed" (FIR-851)
- Concurrency limited scrapes do not show up in the `total` immediately
=> fix(crawl-status): consider concurrency limited jobs as prioritized (FIR-851)

apps/api/src/__tests__/snips/map.test.ts, apps/api/src/lib/validateUrl.ts
Fixes `sitemapOnly`'s faithfulness to the real sitemap, and also should improve Extract for sites that use URLs like `https://example.com/product?id=<xyz>` for product pages/anything that needs to be multi-entity extracted.
=> fix(map): do not remove query parameters from results (FIR-1015)

apps/api/src/__tests__/snips/scrape.test.ts, apps/api/src/scraper/scrapeURL/engines/fire-engine/index.ts
If a user performs page-manipulating actions in the `actions` fields, they usually want their `screenshot` to capture after the actions were made, not before. Fixes a few support tickets.
=> fix(scrapeURL/fire-engine): perform format screenshot after specified actions (FIR-985)

apps/api/src/__tests__/snips/batch-scrape.test.ts, apps/api/src/__tests__/snips/scrape.test.ts, apps/api/src/controllers/v1/types.ts
Fixes #1091 as well as some other complaints.
=> fix(v1/types): fix extract -> json rename (FIR-1072)

apps/api/src/lib/concurrency-limit.ts, apps/api/src/services/queue-jobs.ts, apps/api/src/services/queue-worker.ts
This works more analogous to how BullMQ does job stall detection, and makes it impossible for a job to be stuck taking up a concurrency limit space if it suddenly dies. (for more than 60 seconds.)
=> fix(concurrency-limit): move to renewing a lock on each active job instead of estimating time to complete (FIR-1075)

apps/api/src/controllers/v1/crawl-status-ws.ts, apps/api/src/controllers/v1/crawl-status.ts, apps/api/src/controllers/v1/extract-status.ts, apps/api/src/lib/extract/extraction-service.ts, apps/api/src/services/queue-service.ts, apps/api/src/services/queue-worker.ts
The goal of this branch would be to support retrieving the crawl and extract data, even if there is no supabase for persistant storage and db authentication.
Things I'm not sure of:
* Does this make sense or should we be working towards relying on supabase, even for self-hosted?
* There doesn't appear to be any types representing what is stored in redis with the job results. Am i missing that somewhere?
```
Here is an error from extract/{id}: 
> GET http://10.0.0.4:3002/v1/extract/2820aba6-c6eb-4115-83d5-53b98a17b5aa
< 500 Internal Server Error
< x-powered-by: Express
< access-control-allow-origin: *
< content-type: application/json; charset=utf-8
< content-length: 155
< etag: W/"9b-ATFXC27oGwA7oeVlivs77BM3h9g"
< date: Wed, 05 Feb 2025 11:26:53 GMT
< connection: close
returning 
{ …
```
=> Support /extract and /crawl for self-hosted (FIR-1097)

apps/python-sdk/firecrawl/firecrawl.py
list[str] is not supported in Python 3.8
=> Use correct list typing for py 3.8 support

.github/workflows/test-server-self-host.yml, apps/api/src/search/index.ts, apps/api/src/search/searxng.ts
Fixes #1145 
SearXNG has to be configured with json format
It adds 3 new var env:
* SEARXNG_ENGINES see https://docs.searxng.org/user/configured_engines.html
* SEARXNG_CATEGORIES see https://docs.searxng.org/user/configured_engines.html
* SEARXNG_ENDPOINT=https://your-searxng-instance
=> Add searxng for search endpoint

apps/api/src/__tests__/snips/scrape.test.ts, apps/api/src/lib/crawl-redis.ts
Now also ignores `"excludePaths": [""]` which was previously causing issues.
=> fix(crawl-redis): ignore empty includes/excludes

apps/api/src/index.ts, apps/api/src/services/billing/batch_billing.ts, apps/api/src/services/billing/credit_billing.ts, apps/api/src/services/billing/queue-billing.ts, apps/api/src/services/indexing/index-worker.ts, apps/api/src/services/queue-service.ts, apps/api/src/services/queue-worker.ts
This PR introduces a new batch billing system to streamline and optimize billing operations. Instead of processing each billing operation individually, the system aggregates them into batches for improved efficiency and reduced system load.
- **New Module:**  
- A dedicated `batch_billing.ts` file has been added to handle all batch billing operations.
- **Batch Aggregation:**  
- Billing operations are stored in a Redis list.
- Operations are grouped by `team_id`, `subscription_id`, and `is_extract`.
- Total credits are summed up for each group, allowing billing to be processed collectively.
- **Locking Mechanism:**  
- A Redis-based lock ensures that only one batch is processed at a time, preventing concurrent processing conflicts.
- **Periodic Processing:**  
- A timer (`setInterval`) …
=> (feat/batch-billing) Batch billing

apps/api/src/scraper/WebScraper/crawler.ts, apps/api/src/services/queue-worker.ts
Fixes... crawling our docs on Pylon :D
Also adds debugging because I've added these log statements like 15 times in the last 3 months.
See comment for details
=> feat(crawler): handle cross-origin redirects differently than same-origin redirects

README.md
The documentation example has a "supports_SSO" field that is specified neither in the prompt nor in the schema.
Removing it will make the docs more understandable.
=> docs: remove undefined "required" field

apps/api/src/search/searxng.ts
If categories is set, then the engines parameters don't have an effect.
You must use either categories OR engines. I propose to remove the default value for categories so the user can set en engine using the env var
=> Fix SearxNG categories

apps/api/requests.http, apps/api/src/controllers/v1/types.ts, apps/api/src/search/googlesearch.ts
- Introduced a new POST endpoint for searching with a query and limit
- Updated the maximum limit for search results from 20 to 50 in the request schema
- Adjusted the default number of results in the Google search function from 7 to 5
=> feat(api/search): add search endpoint and update request limits

apps/python-sdk/firecrawl/firecrawl.py
Closes https://github.com/mendableai/firecrawl/issues/1496
This PR updates `scrape_url` and `batch_scrape_urls` in `AsyncFirecrawlApp` to use `_async_monitor_job_status` for asynchronous monitoring of job statuses.
=> Use `_async_monitor_job_status` in `AsyncFirecrawlApp`

apps/python-sdk/firecrawl/firecrawl.py
The API endpoint `batch/scrape` supports the webhook param, this PR aligns the python client to support this.
Noticed webhook support missing when we upgraded the `firecrawl-py` package in our project recently, webhooks stopped working and we got the error message `Unsupported parameter(s) for async_batch_scrape_urls: webhook`. This PR makes it work again. 
Noticed that the tests look a bit outdated for the python stuff, so didn't touch those. Let me know if you want a test case for this.
=> [python-sdk] Webhook param for batch scrape 

apps/api/src/lib/generic-ai.ts
Since #1462 has been merged, it's not possible anymore to use an OpenAI compatible API. Just reuse what was done in #1245.
=> create openAI provider using base url parameter

apps/api/src/controllers/v0/search.ts, apps/api/src/controllers/v1/search.ts
It was only missing on search, seems like.
=> fix(api/search): log page options correctly (FIR-2015)

apps/api/src/scraper/scrapeURL/engines/docx/index.ts, apps/api/src/scraper/scrapeURL/engines/fetch/index.ts, apps/api/src/scraper/scrapeURL/engines/fire-engine/checkStatus.ts, apps/api/src/scraper/scrapeURL/engines/fire-engine/delete.ts, apps/api/src/scraper/scrapeURL/engines/fire-engine/index.ts, apps/api/src/scraper/scrapeURL/engines/pdf/index.ts, apps/api/src/scraper/scrapeURL/engines/playwright/index.ts, apps/api/src/services/queue-worker.ts
- Adds stricter timeouts via the increased use of `AbortSignal`s on `fetch`es
- Adds a networking check to `/liveness` on the workers to let Kubernetes know if the worker has zombified
- Checking against the API is fine, since if the actual API goes down, it doesn't matter much whether the workers are up or not.
=> hotfix: kill zombie workers, respect timeouts better (FIR-2034)

apps/api/src/services/queue-worker.ts
Crawls were not finished if some URLs could potentially be added, even if they turned out to be not addable after adding them. This fixes `crawl.completed` not going out for a customer.
=> fix(queue-worker): finish crawl if all addable URLs were already locked (FIR-1936)

apps/api/src/services/queue-worker.ts
Should resolve people going grossly over the concurrency limit. Adds a pre-insert cc check, only inserts a job from the queue if we're under the limit. May result in going *slightly* over the limit, should never cause underrunning of the active jobs.
=> feat(queue-worker/afterJobDone): improved ccq insert logic (FIR-2082)

apps/api/src/routes/v1.ts
This is what’s been causing the weird insufficient credits errors.
=> fix(v1): check credits variable scope collision

apps/api/src/controllers/v1/__tests__/urlValidation.test.ts, apps/api/src/controllers/v1/types.ts
The existing URL validation didn't support valid URLs like http://xn--1lqv92a901a.xn--ses554g/.
=> Allow international URLs to pass validation

apps/api/src/services/billing/auto_charge.ts
"Increment hourly counter and set expiry if it doesn't exist” is untrue — the command used just sets the expiry over and over again every time it’s called. Added “NX” to alter to intended behaviour.
=> fix(auto_charge): bad hourly counter logic

docker-compose.yaml
Add `ENV: local` to docker-compose services to ensure correct HTTP protocol in API response URLs.
The API code checks `process.env.ENV === "local"` to determine whether to use the request's protocol or force `https://`. Without `ENV=local` set in the Docker environment, the API incorrectly defaults to `https://` in response URLs, even for `http://` requests.
=> Fix protocol change in firecrawl services

apps/api/src/lib/crawl-redis.ts, apps/api/src/scraper/scrapeURL/engines/fire-engine/index.ts
- Fixed incorrect function names passed to `logger.child()`.
=> fix(logger): correct method names in logger.child calls

apps/api/src/scraper/scrapeURL/index.ts, apps/api/src/scraper/scrapeURL/lib/fetch.ts
timeout cutoffs that occured on our end via AbortSignal were not parsed properly
=> fix(api): f-e timeout handling
